/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.84
 * Generated at: 2023-12-31 15:05:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Home Page</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"main.css\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\"\r\n");
      out.write("	rel=\"stylesheet\" />\r\n");
      out.write("<!-- Google Fonts -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\" />\r\n");
      out.write("<!-- MDB -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/7.1.0/mdb.min.css\"\r\n");
      out.write("	rel=\"stylesheet\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<!-- Navbar -->\r\n");
      out.write("	<nav class=\"navbar navbar-expand-lg navbar-light bg-body-tertiary\"\r\n");
      out.write("		style=\"background-color: #3498db;\">\r\n");
      out.write("		<!-- Container wrapper -->\r\n");
      out.write("		<div class=\"container-fluid\">\r\n");
      out.write("			<!-- Toggle button -->\r\n");
      out.write("			<button data-mdb-collapse-init class=\"navbar-toggler\" type=\"button\"\r\n");
      out.write("				data-mdb-target=\"#navbarSupportedContent\"\r\n");
      out.write("				aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\r\n");
      out.write("				aria-label=\"Toggle navigation\">\r\n");
      out.write("				<i class=\"fas fa-bars\"></i>\r\n");
      out.write("			</button>\r\n");
      out.write("\r\n");
      out.write("			<!-- Collapsible wrapper -->\r\n");
      out.write("			<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("				<!-- Navbar brand -->\r\n");
      out.write("				<a class=\"navbar-brand mt-2 mt-lg-0\" href=\"home.jsp\"> <img\r\n");
      out.write("					src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/black.png\"\r\n");
      out.write("					height=\"45\" alt=\"Logo\" loading=\"lazy\" />\r\n");
      out.write("				</a>\r\n");
      out.write("\r\n");
      out.write("				<!-- Left links -->\r\n");
      out.write("				<ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link\" href=\"products\">Products</a>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("						href=\"addNewProduct.jsp\">Add new Product</a></li>\r\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link\" href=\"profile.jsp\">My\r\n");
      out.write("							Profile</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- Collapsible wrapper -->\r\n");
      out.write("\r\n");
      out.write("			<!-- Right elements -->\r\n");
      out.write("			<div class=\"d-flex align-items-center\">\r\n");
      out.write("				<!-- Icon -->\r\n");
      out.write("				<a class=\"text-reset me-3\" href=\"login.jsp\"> Login </a> <a\r\n");
      out.write("					class=\"text-reset me-3\" href=\"register.jsp\"> Register </a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- Right elements -->\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- Container wrapper -->\r\n");
      out.write("	</nav>\r\n");
      out.write("	<!-- Navbar -->\r\n");
      out.write("\r\n");
      out.write("	<div class='hero_section'>\r\n");
      out.write("		<h3 class='hero-hed'>CLASSIC & TIMELESS HAND CRAFT GOODS</h3>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<div class='container1'>\r\n");
      out.write("		<p>\"YOU MUST JUDGE A MAN BY THE WORK OF HIS HANDS.\"</p>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<div class='container2'>\r\n");
      out.write("		<div class='inner'>\r\n");
      out.write("			<h3>FEATURED PRODUCTS</h3>\r\n");
      out.write("			<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem\r\n");
      out.write("				accusantium doloremque.</p>\r\n");
      out.write("			<button>VIEW ALL</button>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class='inner' id= 'bx1'>\r\n");
      out.write("			<div class=\"card\">\r\n");
      out.write("				<img\r\n");
      out.write("					src=\"https://images.unsplash.com/photo-1621371205896-3082fa811d54?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fGhhbmRjcmFmdHxlbnwwfDB8MHx8fDA%3D\"\r\n");
      out.write("					class=\"card-img-top\" alt=\"Product Image\">\r\n");
      out.write("				<div class=\"card-body\">\r\n");
      out.write("					<h5 class=\"card-title\">Hand-sewn Leather Wallet in Coffee</h5>\r\n");
      out.write("					<p class=\"card-text\">Moose</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class='inner' id= 'bx2'>\r\n");
      out.write("			<div class=\"card\" >\r\n");
      out.write("				<img\r\n");
      out.write("					src=\"https://images.unsplash.com/photo-1493106641515-6b5631de4bb9?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8aGFuZCUyMGNyYWZ0fGVufDB8MHwwfHx8MA%3D%3D\"\r\n");
      out.write("					class=\"card-img-top\" alt=\"Product Image\">\r\n");
      out.write("				<div class=\"card-body\">\r\n");
      out.write("					<h5 class=\"card-title\">Hand-sewn Leather Wallet in Coffee</h5>\r\n");
      out.write("					<p class=\"card-text\">Moose</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class='inner' id= 'bx3'>\r\n");
      out.write("			<div class=\"card\">\r\n");
      out.write("				<img\r\n");
      out.write("					src=\"https://images.unsplash.com/photo-1568288796918-03e7d93306bd?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fGhhbmQlMjBjcmFmdHxlbnwwfDB8MHx8fDA%3D\"\r\n");
      out.write("					class=\"card-img-top\" alt=\"Product Image\">\r\n");
      out.write("				<div class=\"card-body\">\r\n");
      out.write("					<h5 class=\"card-title\">Hand-sewn Leather Wallet in Coffee</h5>\r\n");
      out.write("					<p class=\"card-text\">Moose</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<div class='gallery'>\r\n");
      out.write("	<p class='gal-head'>Gallery</p>\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("				<div class=\"col-md-3 mb-4\">\r\n");
      out.write("					<div class=\"card\">\r\n");
      out.write("						<img src=\"https://images.unsplash.com/photo-1621371205896-3082fa811d54?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fGhhbmRjcmFmdHxlbnwwfDB8MHx8fDA%3D\" class=\"card-img-top\"\r\n");
      out.write("							alt=\"Product Image\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-3 mb-4\">\r\n");
      out.write("					<div class=\"card\">\r\n");
      out.write("						<img src=\"https://images.unsplash.com/photo-1621371205896-3082fa811d54?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fGhhbmRjcmFmdHxlbnwwfDB8MHx8fDA%3D\" class=\"card-img-top\"\r\n");
      out.write("							alt=\"Product Image\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-3 mb-4\">\r\n");
      out.write("					<div class=\"card\">\r\n");
      out.write("						<img src=\"https://images.unsplash.com/photo-1621371205896-3082fa811d54?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fGhhbmRjcmFmdHxlbnwwfDB8MHx8fDA%3D\" class=\"card-img-top\"\r\n");
      out.write("							alt=\"Product Image\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-3 mb-4\">\r\n");
      out.write("					<div class=\"card\">\r\n");
      out.write("						<img src=\"https://images.unsplash.com/photo-1621371205896-3082fa811d54?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fGhhbmRjcmFmdHxlbnwwfDB8MHx8fDA%3D\" class=\"card-img-top\"\r\n");
      out.write("							alt=\"Product Image\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("		\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-md-3 mb-4\">\r\n");
      out.write("					<div class=\"card\">\r\n");
      out.write("						<img src=\"https://images.unsplash.com/photo-1621371205896-3082fa811d54?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fGhhbmRjcmFmdHxlbnwwfDB8MHx8fDA%3D\" class=\"card-img-top\"\r\n");
      out.write("							alt=\"Product Image\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-3 mb-4\">\r\n");
      out.write("					<div class=\"card\">\r\n");
      out.write("						<img src=\"https://images.unsplash.com/photo-1621371205896-3082fa811d54?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fGhhbmRjcmFmdHxlbnwwfDB8MHx8fDA%3D\" class=\"card-img-top\"\r\n");
      out.write("							alt=\"Product Image\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-3 mb-4\">\r\n");
      out.write("					<div class=\"card\">\r\n");
      out.write("						<img src=\"https://images.unsplash.com/photo-1621371205896-3082fa811d54?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fGhhbmRjcmFmdHxlbnwwfDB8MHx8fDA%3D\" class=\"card-img-top\"\r\n");
      out.write("							alt=\"Product Image\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-3 mb-4\">\r\n");
      out.write("					<div class=\"card\">\r\n");
      out.write("						<img src=\"https://images.unsplash.com/photo-1621371205896-3082fa811d54?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fGhhbmRjcmFmdHxlbnwwfDB8MHx8fDA%3D\" class=\"card-img-top\"\r\n");
      out.write("							alt=\"Product Image\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("		\r\n");
      out.write("			</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Footer -->\r\n");
      out.write("\r\n");
      out.write("	<footer class=\"text-center text-lg-start bg-dark text-white\">\r\n");
      out.write("		<!-- Section: Social media -->\r\n");
      out.write("		<section\r\n");
      out.write("			class=\"d-flex justify-content-center justify-content-lg-between p-4 border-bottom\">\r\n");
      out.write("			<!-- Left -->\r\n");
      out.write("			<div class=\"me-5 d-none d-lg-block\">\r\n");
      out.write("				<span>Get connected with us on social networks:</span>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- Left -->\r\n");
      out.write("\r\n");
      out.write("			<!-- Right -->\r\n");
      out.write("			<div>\r\n");
      out.write("				<a href=\"\" class=\"me-4 text-reset\"> <i class=\"fab fa-facebook-f\"></i>\r\n");
      out.write("				</a> <a href=\"\" class=\"me-4 text-reset\"> <i class=\"fab fa-twitter\"></i>\r\n");
      out.write("				</a> <a href=\"\" class=\"me-4 text-reset\"> <i class=\"fab fa-google\"></i>\r\n");
      out.write("				</a> <a href=\"\" class=\"me-4 text-reset\"> <i class=\"fab fa-instagram\"></i>\r\n");
      out.write("				</a> <a href=\"\" class=\"me-4 text-reset\"> <i class=\"fab fa-linkedin\"></i>\r\n");
      out.write("				</a> <a href=\"\" class=\"me-4 text-reset\"> <i class=\"fab fa-github\"></i>\r\n");
      out.write("				</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- Right -->\r\n");
      out.write("		</section>\r\n");
      out.write("		<!-- Section: Social media -->\r\n");
      out.write("\r\n");
      out.write("		<!-- Section: Links  -->\r\n");
      out.write("		<section class=\"\">\r\n");
      out.write("			<div class=\"container text-center text-md-start mt-5\">\r\n");
      out.write("				<!-- Grid row -->\r\n");
      out.write("				<div class=\"row mt-3\">\r\n");
      out.write("					<!-- Grid column -->\r\n");
      out.write("					<div class=\"col-md-3 col-lg-4 col-xl-3 mx-auto mb-4\">\r\n");
      out.write("						<!-- Content -->\r\n");
      out.write("						<h6 class=\"text-uppercase fw-bold mb-4\">\r\n");
      out.write("							<i class=\"fas fa-gem me-3\"></i>Company name\r\n");
      out.write("						</h6>\r\n");
      out.write("						<p>Here you can use rows and columns to organize your footer\r\n");
      out.write("							content. Lorem ipsum dolor sit amet, consectetur adipisicing\r\n");
      out.write("							elit.</p>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- Grid column -->\r\n");
      out.write("\r\n");
      out.write("					<!-- Grid column -->\r\n");
      out.write("					<div class=\"col-md-2 col-lg-2 col-xl-2 mx-auto mb-4\">\r\n");
      out.write("						<!-- Links -->\r\n");
      out.write("						<h6 class=\"text-uppercase fw-bold mb-4\">Products</h6>\r\n");
      out.write("						<p>\r\n");
      out.write("							<a href=\"#!\" class=\"text-reset\">Angular</a>\r\n");
      out.write("						</p>\r\n");
      out.write("						<p>\r\n");
      out.write("							<a href=\"#!\" class=\"text-reset\">React</a>\r\n");
      out.write("						</p>\r\n");
      out.write("						<p>\r\n");
      out.write("							<a href=\"#!\" class=\"text-reset\">Vue</a>\r\n");
      out.write("						</p>\r\n");
      out.write("						<p>\r\n");
      out.write("							<a href=\"#!\" class=\"text-reset\">Laravel</a>\r\n");
      out.write("						</p>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- Grid column -->\r\n");
      out.write("\r\n");
      out.write("					<!-- Grid column -->\r\n");
      out.write("					<div class=\"col-md-3 col-lg-2 col-xl-2 mx-auto mb-4\">\r\n");
      out.write("						<!-- Links -->\r\n");
      out.write("						<h6 class=\"text-uppercase fw-bold mb-4\">Useful links</h6>\r\n");
      out.write("						<p>\r\n");
      out.write("							<a href=\"#!\" class=\"text-reset\">Pricing</a>\r\n");
      out.write("						</p>\r\n");
      out.write("						<p>\r\n");
      out.write("							<a href=\"#!\" class=\"text-reset\">Settings</a>\r\n");
      out.write("						</p>\r\n");
      out.write("						<p>\r\n");
      out.write("							<a href=\"#!\" class=\"text-reset\">Orders</a>\r\n");
      out.write("						</p>\r\n");
      out.write("						<p>\r\n");
      out.write("							<a href=\"#!\" class=\"text-reset\">Help</a>\r\n");
      out.write("						</p>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- Grid column -->\r\n");
      out.write("\r\n");
      out.write("					<!-- Grid column -->\r\n");
      out.write("					<div class=\"col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4\">\r\n");
      out.write("						<!-- Links -->\r\n");
      out.write("						<h6 class=\"text-uppercase fw-bold mb-4\">Contact</h6>\r\n");
      out.write("						<p>\r\n");
      out.write("							<i class=\"fas fa-home me-3\"></i> New York, NY 10012, US\r\n");
      out.write("						</p>\r\n");
      out.write("						<p>\r\n");
      out.write("							<i class=\"fas fa-envelope me-3\"></i> info@example.com\r\n");
      out.write("						</p>\r\n");
      out.write("						<p>\r\n");
      out.write("							<i class=\"fas fa-phone me-3\"></i> + 01 234 567 88\r\n");
      out.write("						</p>\r\n");
      out.write("						<p>\r\n");
      out.write("							<i class=\"fas fa-print me-3\"></i> + 01 234 567 89\r\n");
      out.write("						</p>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- Grid column -->\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- Grid row -->\r\n");
      out.write("			</div>\r\n");
      out.write("		</section>\r\n");
      out.write("		<!-- Section: Links  -->\r\n");
      out.write("\r\n");
      out.write("		<!-- Copyright -->\r\n");
      out.write("		<div class=\"text-center p-4\"\r\n");
      out.write("			style=\"background-color: rgba(0, 0, 0, 0.05);\">\r\n");
      out.write("			© 2021 Copyright: <a class=\"text-reset fw-bold\"\r\n");
      out.write("				href=\"https://mdbootstrap.com/\">MDBootstrap.com</a>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- Copyright -->\r\n");
      out.write("	</footer>\r\n");
      out.write("	<!-- Footer -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- MDB -->\r\n");
      out.write("	<script type=\"text/javascript\"\r\n");
      out.write("		src=\"https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/7.1.0/mdb.umd.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
