/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.84
 * Generated at: 2023-12-31 15:08:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class profile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1703755842936L));
    _jspx_dependants.put("jar:file:/E:/Java%20workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Nanobotz_web_application/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.4.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"main.css\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\"\r\n");
      out.write("	rel=\"stylesheet\" />\r\n");
      out.write("<!-- Google Fonts -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\" />\r\n");
      out.write("<!-- MDB -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/7.1.0/mdb.min.css\"\r\n");
      out.write("	rel=\"stylesheet\" />\r\n");
      out.write("<script>\r\n");
      out.write("	$(document).ready(function() {\r\n");
      out.write("		// Check if the page has been loaded before\r\n");
      out.write("		var isFirstVisit = sessionStorage.getItem('isFirstVisit');\r\n");
      out.write("\r\n");
      out.write("		if (!isFirstVisit) {\r\n");
      out.write("			// Set the flag in session storage\r\n");
      out.write("			sessionStorage.setItem('isFirstVisit', 'true');\r\n");
      out.write("\r\n");
      out.write("			// Perform the AJAX call only on the first visit or refresh\r\n");
      out.write("			performAjaxCall();\r\n");
      out.write("		} else {\r\n");
      out.write("			// Reset the flag to false on page refresh\r\n");
      out.write("			sessionStorage.removeItem('isFirstVisit');\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		// Function to perform AJAX call\r\n");
      out.write("		function performAjaxCall() {\r\n");
      out.write("			var UID = $('#hiddenUID').val();\r\n");
      out.write("\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				type : 'POST',\r\n");
      out.write("				url : 'profile',\r\n");
      out.write("				data : {\r\n");
      out.write("					uid : UID\r\n");
      out.write("				},\r\n");
      out.write("				success : function(response) {\r\n");
      out.write("					console.log(response);\r\n");
      out.write("					$('#mainContainer').html(response);\r\n");
      out.write("\r\n");
      out.write("				},\r\n");
      out.write("				error : function(error) {\r\n");
      out.write("					console.error('Error:', error);\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("	});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- Hidden input field to store the session attribute value -->\r\n");
      out.write("	<input type=\"hidden\" id=\"hiddenUID\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.UID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("\r\n");
      out.write("	<!-- Main container for both navbar and profile details -->\r\n");
      out.write("	<div id=\"mainContainer\">\r\n");
      out.write("		<!-- Navbar -->\r\n");
      out.write("		<nav class=\"navbar navbar-expand-lg navbar-light bg-body-tertiary\"\r\n");
      out.write("			style=\"background-color: #3498db;\">\r\n");
      out.write("			<!-- Container wrapper -->\r\n");
      out.write("			<div class=\"container-fluid\">\r\n");
      out.write("				<!-- Toggle button -->\r\n");
      out.write("				<button data-mdb-collapse-init class=\"navbar-toggler\" type=\"button\"\r\n");
      out.write("					data-mdb-target=\"#navbarSupportedContent\"\r\n");
      out.write("					aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\r\n");
      out.write("					aria-label=\"Toggle navigation\">\r\n");
      out.write("					<i class=\"fas fa-bars\"></i>\r\n");
      out.write("				</button>\r\n");
      out.write("\r\n");
      out.write("				<!-- Collapsible wrapper -->\r\n");
      out.write("				<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("					<!-- Navbar brand -->\r\n");
      out.write("					<a class=\"navbar-brand mt-2 mt-lg-0\" href=\"home.jsp\"> <img\r\n");
      out.write("						src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/black.png\"\r\n");
      out.write("						height=\"45\" alt=\"Logo\" loading=\"lazy\" />\r\n");
      out.write("					</a>\r\n");
      out.write("\r\n");
      out.write("					<!-- Left links -->\r\n");
      out.write("					<ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("						<li class=\"nav-item\"><a class=\"nav-link\" href=\"products\">Products</a>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("							href=\"addNewProduct.jsp\">Add new Product</a></li>\r\n");
      out.write("						<li class=\"nav-item\"><a class=\"nav-link\" href=\"profile.jsp\">My\r\n");
      out.write("								Profile</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- Collapsible wrapper -->\r\n");
      out.write("\r\n");
      out.write("				<!-- Right elements -->\r\n");
      out.write("				<div class=\"d-flex align-items-center\">\r\n");
      out.write("					<!-- Icon -->\r\n");
      out.write("					<a class=\"text-reset me-3\" href=\"login.jsp\"> Login </a> <a\r\n");
      out.write("						class=\"text-reset me-3\" href=\"register.jsp\"> Register </a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- Right elements -->\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- Container wrapper -->\r\n");
      out.write("		</nav>\r\n");
      out.write("		<!-- Navbar -->\r\n");
      out.write("\r\n");
      out.write("		<!-- Profile details container -->\r\n");
      out.write("		<div id=\"profileDetailsContainer\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<div class=\"profile-card\" style=\"width: 40%; margin: 50px auto; padding: 20px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); background-color: #fff; border-radius: 8px; text-align: justify;\">\r\n");
      out.write("		    <h2>User Profile</h2>\r\n");
      out.write("		    <div class=\"profile-details\">\r\n");
      out.write("		        ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("		    </div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- Footer -->\r\n");
      out.write("\r\n");
      out.write("		<footer class=\"text-center text-lg-start bg-dark text-white\">\r\n");
      out.write("			<!-- Section: Social media -->\r\n");
      out.write("			<section\r\n");
      out.write("				class=\"d-flex justify-content-center justify-content-lg-between p-4 border-bottom\">\r\n");
      out.write("				<!-- Left -->\r\n");
      out.write("				<div class=\"me-5 d-none d-lg-block\">\r\n");
      out.write("					<span>Get connected with us on social networks:</span>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- Left -->\r\n");
      out.write("\r\n");
      out.write("				<!-- Right -->\r\n");
      out.write("				<div>\r\n");
      out.write("					<a href=\"\" class=\"me-4 text-reset\"> <i\r\n");
      out.write("						class=\"fab fa-facebook-f\"></i>\r\n");
      out.write("					</a> <a href=\"\" class=\"me-4 text-reset\"> <i class=\"fab fa-twitter\"></i>\r\n");
      out.write("					</a> <a href=\"\" class=\"me-4 text-reset\"> <i class=\"fab fa-google\"></i>\r\n");
      out.write("					</a> <a href=\"\" class=\"me-4 text-reset\"> <i\r\n");
      out.write("						class=\"fab fa-instagram\"></i>\r\n");
      out.write("					</a> <a href=\"\" class=\"me-4 text-reset\"> <i class=\"fab fa-linkedin\"></i>\r\n");
      out.write("					</a> <a href=\"\" class=\"me-4 text-reset\"> <i class=\"fab fa-github\"></i>\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- Right -->\r\n");
      out.write("			</section>\r\n");
      out.write("			<!-- Section: Social media -->\r\n");
      out.write("\r\n");
      out.write("			<!-- Section: Links  -->\r\n");
      out.write("			<section class=\"\">\r\n");
      out.write("				<div class=\"container text-center text-md-start mt-5\">\r\n");
      out.write("					<!-- Grid row -->\r\n");
      out.write("					<div class=\"row mt-3\">\r\n");
      out.write("						<!-- Grid column -->\r\n");
      out.write("						<div class=\"col-md-3 col-lg-4 col-xl-3 mx-auto mb-4\">\r\n");
      out.write("							<!-- Content -->\r\n");
      out.write("							<h6 class=\"text-uppercase fw-bold mb-4\">\r\n");
      out.write("								<i class=\"fas fa-gem me-3\"></i>Company name\r\n");
      out.write("							</h6>\r\n");
      out.write("							<p>Here you can use rows and columns to organize your footer\r\n");
      out.write("								content. Lorem ipsum dolor sit amet, consectetur adipisicing\r\n");
      out.write("								elit.</p>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- Grid column -->\r\n");
      out.write("\r\n");
      out.write("						<!-- Grid column -->\r\n");
      out.write("						<div class=\"col-md-2 col-lg-2 col-xl-2 mx-auto mb-4\">\r\n");
      out.write("							<!-- Links -->\r\n");
      out.write("							<h6 class=\"text-uppercase fw-bold mb-4\">Products</h6>\r\n");
      out.write("							<p>\r\n");
      out.write("								<a href=\"#!\" class=\"text-reset\">Angular</a>\r\n");
      out.write("							</p>\r\n");
      out.write("							<p>\r\n");
      out.write("								<a href=\"#!\" class=\"text-reset\">React</a>\r\n");
      out.write("							</p>\r\n");
      out.write("							<p>\r\n");
      out.write("								<a href=\"#!\" class=\"text-reset\">Vue</a>\r\n");
      out.write("							</p>\r\n");
      out.write("							<p>\r\n");
      out.write("								<a href=\"#!\" class=\"text-reset\">Laravel</a>\r\n");
      out.write("							</p>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- Grid column -->\r\n");
      out.write("\r\n");
      out.write("						<!-- Grid column -->\r\n");
      out.write("						<div class=\"col-md-3 col-lg-2 col-xl-2 mx-auto mb-4\">\r\n");
      out.write("							<!-- Links -->\r\n");
      out.write("							<h6 class=\"text-uppercase fw-bold mb-4\">Useful links</h6>\r\n");
      out.write("							<p>\r\n");
      out.write("								<a href=\"#!\" class=\"text-reset\">Pricing</a>\r\n");
      out.write("							</p>\r\n");
      out.write("							<p>\r\n");
      out.write("								<a href=\"#!\" class=\"text-reset\">Settings</a>\r\n");
      out.write("							</p>\r\n");
      out.write("							<p>\r\n");
      out.write("								<a href=\"#!\" class=\"text-reset\">Orders</a>\r\n");
      out.write("							</p>\r\n");
      out.write("							<p>\r\n");
      out.write("								<a href=\"#!\" class=\"text-reset\">Help</a>\r\n");
      out.write("							</p>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- Grid column -->\r\n");
      out.write("\r\n");
      out.write("						<!-- Grid column -->\r\n");
      out.write("						<div class=\"col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4\">\r\n");
      out.write("							<!-- Links -->\r\n");
      out.write("							<h6 class=\"text-uppercase fw-bold mb-4\">Contact</h6>\r\n");
      out.write("							<p>\r\n");
      out.write("								<i class=\"fas fa-home me-3\"></i> New York, NY 10012, US\r\n");
      out.write("							</p>\r\n");
      out.write("							<p>\r\n");
      out.write("								<i class=\"fas fa-envelope me-3\"></i> info@example.com\r\n");
      out.write("							</p>\r\n");
      out.write("							<p>\r\n");
      out.write("								<i class=\"fas fa-phone me-3\"></i> + 01 234 567 88\r\n");
      out.write("							</p>\r\n");
      out.write("							<p>\r\n");
      out.write("								<i class=\"fas fa-print me-3\"></i> + 01 234 567 89\r\n");
      out.write("							</p>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- Grid column -->\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- Grid row -->\r\n");
      out.write("				</div>\r\n");
      out.write("			</section>\r\n");
      out.write("			<!-- Section: Links  -->\r\n");
      out.write("\r\n");
      out.write("			<!-- Copyright -->\r\n");
      out.write("			<div class=\"text-center p-4\"\r\n");
      out.write("				style=\"background-color: rgba(0, 0, 0, 0.05);\">\r\n");
      out.write("				© 2021 Copyright: <a class=\"text-reset fw-bold\"\r\n");
      out.write("					href=\"https://mdbootstrap.com/\">MDBootstrap.com</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- Copyright -->\r\n");
      out.write("		</footer>\r\n");
      out.write("		<!-- Footer -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- MDB -->\r\n");
      out.write("	<script type=\"text/javascript\"\r\n");
      out.write("		src=\"https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/7.1.0/mdb.umd.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /profile.jsp(123,10) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("profile");
      // /profile.jsp(123,10) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/profile.jsp(123,10) '${profileDetails}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${profileDetails}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("		            <p>\r\n");
            out.write("		                <strong>Profile Id:</strong> ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${profile.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\r\n");
            out.write("		            </p>\r\n");
            out.write("		            <p>\r\n");
            out.write("		                <strong>Name:</strong> ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${profile.salutation}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(".\r\n");
            out.write("		                ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${profile.firstname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(' ');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${profile.lastname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\r\n");
            out.write("		            </p>\r\n");
            out.write("		            <p>\r\n");
            out.write("		                <strong>Telephone Number:</strong> ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${profile.tell}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\r\n");
            out.write("		            </p>\r\n");
            out.write("		            <p>\r\n");
            out.write("		                <strong>Address:</strong> ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${profile.address}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\r\n");
            out.write("		            </p>\r\n");
            out.write("		            <p>\r\n");
            out.write("		                <strong>Email:</strong> ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${profile.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\r\n");
            out.write("		            </p>\r\n");
            out.write("		            <p>\r\n");
            out.write("		                <strong>Username:</strong> ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${profile.username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\r\n");
            out.write("		            </p>\r\n");
            out.write("		            <p>\r\n");
            out.write("		                <strong>Points:</strong> ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${profile.points}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\r\n");
            out.write("		            </p>\r\n");
            out.write("		        ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
