/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.84
 * Generated at: 2023-12-31 10:34:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Register Page</title>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js\">\r\n");
      out.write("</script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"main.css\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\"\r\n");
      out.write("	rel=\"stylesheet\" />\r\n");
      out.write("<!-- Google Fonts -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\" />\r\n");
      out.write("<!-- MDB -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/7.1.0/mdb.min.css\"\r\n");
      out.write("	rel=\"stylesheet\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write(" 	<!-- Section: Design Block -->\r\n");
      out.write("	<section class=\"background-radial-gradient overflow-hidden\"\r\n");
      out.write("		style=\"height: 100vh; width: 100%;\">\r\n");
      out.write("		<style>\r\n");
      out.write(".background-radial-gradient {\r\n");
      out.write("background-color: hsl(218, 41%, 15%);\r\n");
      out.write("background-image: radial-gradient(650px circle at 0% 0%, hsl(218, 41%, 50%) 15%, hsl(218, 41%, 40%) 35%, hsl(218, 41%, 30%) 75%, hsl(218, 41%, 25%) 80%, transparent 100%),\r\n");
      out.write("                  radial-gradient(1250px circle at 100% 100%, hsl(218, 41%, 60%) 15%, hsl(218, 41%, 40%) 35%, hsl(218, 41%, 30%) 75%, hsl(218, 41%, 25%) 80%, transparent 100%);\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("#radius-shape-1 {\r\n");
      out.write("	height: 220px;\r\n");
      out.write("	width: 220px;\r\n");
      out.write("	top: -60px;\r\n");
      out.write("	left: -130px;\r\n");
      out.write("	background: radial-gradient(#44006b, #ad1fff);\r\n");
      out.write("	overflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#radius-shape-2 {\r\n");
      out.write("	border-radius: 38% 62% 63% 37%/70% 33% 67% 30%;\r\n");
      out.write("	bottom: -60px;\r\n");
      out.write("	right: -110px;\r\n");
      out.write("	width: 300px;\r\n");
      out.write("	height: 300px;\r\n");
      out.write("	background: radial-gradient(#44006b, #ad1fff);\r\n");
      out.write("	overflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bg-glass {\r\n");
      out.write("	background-color: hsla(0, 0%, 100%, 0.9) !important;\r\n");
      out.write("	backdrop-filter: saturate(200%) blur(25px);\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("		<div\r\n");
      out.write("			class=\"container px-4 py-5 px-md-5 text-center text-lg-start my-5\">\r\n");
      out.write("			<div class=\"row gx-lg-5 align-items-center mb-5\">\r\n");
      out.write("				<div class=\"col-lg-6 mb-5 mb-lg-0\" style=\"z-index: 10\">\r\n");
      out.write("					<h1 class=\"my-5 display-5 fw-bold ls-tight\"\r\n");
      out.write("						style=\"color: hsl(218, 81%, 95%)\">\r\n");
      out.write("						The best offer <br /> <span style=\"color: hsl(218, 81%, 75%)\">for\r\n");
      out.write("							your business</span>\r\n");
      out.write("					</h1>\r\n");
      out.write("					<p class=\"mb-4 opacity-70\" style=\"color: hsl(218, 81%, 85%)\">\r\n");
      out.write("						Lorem ipsum dolor, sit amet consectetur adipisicing elit.\r\n");
      out.write("						Temporibus, expedita iusto veniam atque, magni tempora mollitia\r\n");
      out.write("						dolorum consequatur nulla, neque debitis eos reprehenderit quasi\r\n");
      out.write("						ab ipsum nisi dolorem modi. Quos?</p>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-lg-6 mb-5 mb-lg-0 position-relative\">\r\n");
      out.write("					<div id=\"radius-shape-1\"\r\n");
      out.write("						class=\"position-absolute rounded-circle shadow-5-strong\"></div>\r\n");
      out.write("					<div id=\"radius-shape-2\" class=\"position-absolute shadow-5-strong\"></div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"card bg-glass\">\r\n");
      out.write("						<div class=\"card-body px-4 py-5 px-md-5\">\r\n");
      out.write("							<form action='register' method='post' onsubmit=\"return validateForm()\">\r\n");
      out.write("								<!-- Email input -->\r\n");
      out.write("								<h4 style=\"margin-bottom: 20px;\">\r\n");
      out.write("									<center>Connect With Us </center>\r\n");
      out.write("								</h4>\r\n");
      out.write("								<a  href ='home.jsp'>\r\n");
      out.write("								<img\r\n");
      out.write("						          src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/black.png\"\r\n");
      out.write("						          height=\"45\"\r\n");
      out.write("						          alt=\"Logo\"\r\n");
      out.write("						          loading=\"lazy\"\r\n");
      out.write("						          class= 'logo_img'\r\n");
      out.write("						         \r\n");
      out.write("						        />\r\n");
      out.write("						        </a>\r\n");
      out.write("								<p style=\"text-align: center ;margin-bottom: 20px;\" >Lorem Ipsum is simply dummy text of the printing and\r\n");
      out.write("									typesetting industry. Lorem Ipsum has been the industry's\r\n");
      out.write("									standard dummy text ever since the . </p>\r\n");
      out.write("									\r\n");
      out.write("									\r\n");
      out.write("									\r\n");
      out.write("									<div class=\"row\">\r\n");
      out.write("						                <div class=\"col-md-6 mb-4\">\r\n");
      out.write("						                  <div class=\"form-outline\">\r\n");
      out.write("											  <input type=\"text\" id=\"salutation\" name='salutation' class=\"form-control\" />\r\n");
      out.write("											  <label class=\"form-label\" for=\"form3Example1\">Salutation</label>\r\n");
      out.write("											</div>\r\n");
      out.write("						                </div>\r\n");
      out.write("						                <div class=\"col-md-6 mb-4\">\r\n");
      out.write("						                  <div class=\"form-outline\">\r\n");
      out.write("						                    <input type=\"text\" id=\"email\" name='email' class=\"form-control\" />\r\n");
      out.write("						                    <label class=\"form-label\" for=\"form3Example2\">Email</label>\r\n");
      out.write("						                  </div>\r\n");
      out.write("						                </div>\r\n");
      out.write("						             </div>\r\n");
      out.write("						             <div class=\"row\">\r\n");
      out.write("						                <div class=\"col-md-6 mb-4\">\r\n");
      out.write("						                  <div class=\"form-outline\">\r\n");
      out.write("											  <input type=\"text\" id=\"firstname\" name='firstname' class=\"form-control\" />\r\n");
      out.write("						                    <label class=\"form-label\" for=\"form3Example2\">First Name</label>\r\n");
      out.write("						                  </div>\r\n");
      out.write("						                </div>\r\n");
      out.write("						                <div class=\"col-md-6 mb-4\">\r\n");
      out.write("						                  <div class=\"form-outline\">\r\n");
      out.write("						                    <input type=\"text\" id=\"lastname\" name='lastname' class=\"form-control\" />\r\n");
      out.write("						                    <label class=\"form-label\" for=\"form3Example2\">Last Name</label>\r\n");
      out.write("						                  </div>\r\n");
      out.write("						                </div>\r\n");
      out.write("						             </div>\r\n");
      out.write("						             \r\n");
      out.write("						             <div class=\"row\">\r\n");
      out.write("						                <div class=\"col-md-6 mb-4\">\r\n");
      out.write("						                  <div class=\"form-outline\">\r\n");
      out.write("											  <input type=\"text\" id=\"tele\" name='tell' class=\"form-control\" />\r\n");
      out.write("						                    <label class=\"form-label\" for=\"form3Example2\">Telephone</label>\r\n");
      out.write("						                  </div>\r\n");
      out.write("						                </div>\r\n");
      out.write("						                <div class=\"col-md-6 mb-4\">\r\n");
      out.write("						                  <div class=\"form-outline\">\r\n");
      out.write("						                    <input type=\"text\" id=\"address\" name='address' class=\"form-control\" />\r\n");
      out.write("						                    <label class=\"form-label\" for=\"form3Example2\">Address</label>\r\n");
      out.write("						                  </div>\r\n");
      out.write("						                </div>\r\n");
      out.write("						             </div>\r\n");
      out.write("						             \r\n");
      out.write("						             <div class=\"row\">\r\n");
      out.write("						                <div class=\"col-md-6 mb-4\">\r\n");
      out.write("						                  <div class=\"form-outline\">\r\n");
      out.write("											  <input type=\"text\" id=\"username\" name='username' class=\"form-control\" />\r\n");
      out.write("						                    <label class=\"form-label\" for=\"form3Example2\">UserName</label>\r\n");
      out.write("						                  </div>\r\n");
      out.write("						                </div>\r\n");
      out.write("						                <div class=\"col-md-6 mb-4\">\r\n");
      out.write("						                  <div class=\"form-outline\">\r\n");
      out.write("						                    <input type=\"password\" id=\"pwd\" name='password' class=\"form-control\" />\r\n");
      out.write("                							<label class=\"form-label\" for=\"form3Example4\" name='username'>Password</label>\r\n");
      out.write("						                  </div>\r\n");
      out.write("						                </div>\r\n");
      out.write("						             </div>\r\n");
      out.write("              <!-- Submit button -->\r\n");
      out.write("              					<button type=\"submit\" class=\"btn btn-primary btn-block mb-4\"> Login</button>\r\n");
      out.write("              					<p>Do you have an account? <a href=\"login.jsp\">Login</a></p>\r\n");
      out.write("            </form>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</section>\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" <script>\r\n");
      out.write("function validateForm() {\r\n");
      out.write("    var salutation = document.getElementById(\"salutation\").value;\r\n");
      out.write("    var email = document.getElementById(\"email\").value;\r\n");
      out.write("    var firstname = document.getElementById(\"firstname\").value;\r\n");
      out.write("    var lastname = document.getElementById(\"lastname\").value;\r\n");
      out.write("    var tele = document.getElementById(\"tele\").value;\r\n");
      out.write("    var address = document.getElementById(\"address\").value;\r\n");
      out.write("    var username = document.getElementById(\"username\").value;\r\n");
      out.write("    var pwd = document.getElementById(\"pwd\").value;\r\n");
      out.write("\r\n");
      out.write("    if (username.trim() === \"\" || pwd.trim() === \"\" || salutation.trim() === \"\" || firstname.trim() === \"\" || lastname.trim() === \"\" || tele.trim() === \"\" || address.trim() === \"\"  ) {\r\n");
      out.write("        alert(\"Please fill in required fields..!\");\r\n");
      out.write("        return false;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    return true;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write(" \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
